FROM primekey/ejbca-ce:latest@sha256:591a80079f82dd695e6970eefe5a67d9c21b0d8ae93f2f606bed3efc0f79fce8


#RUN cd /opt && curl http://sourceforge.net/projects/ejbca/files/ejbca6/ejbca_6_2_0/ejbca_ce_6_2_0.zip | unzip 
