_init_run_screen () {

  TTY=$( /usr/bin/tty )
  SCREEN=$( which screen )
 
  if [ "$TTY"  != "not a tty" -a \
       "$TERM" != "screen" -a \
       "$SHLVL" -eq 1 ] 
  then

    if [ -x "$(which screen)" ]; then
       screen -t `hostname` -x -RR remote
    fi

  fi

}

_init_setup_editor () {

  if   [ -x "$(which xemacs)" ]; then
    EDITOR=xemacs
  elif [ -x "$(which emacs)"  ]; then
    EDITOR=emacs
  elif [ -x "$(which vim)"    ]; then
    EDITOR=vim
  else
    EDITOR=vi
  fi

  export EDITOR
}

_init_bash_completion () {

  # Check for bash (and that we haven't already been sourced).
  [ -z "$BASH_VERSION" -o -n "$BASH_COMPLETION" ] && return

  # Check for recent enough version of bash.
  bash=${BASH_VERSION%.*}; bmajor=${bash%.*}; bminor=${bash#*.}

  # Set the path
  #BASH_COMPLETION="${BASH_COMPLETION:-/etc/bash_completion}"
  BASH_COMPLETION=~/.completion/bash_completion
  BASH_COMPLETION_DIR=~/.completion/bash_completion.d/

  # Check for interactive shell.
  if [ -n "$PS1" ]; then
    if [ $bmajor -eq 2 -a $bminor '>' 04 ] || [ $bmajor -gt 2 ]; then
      if [ -r  $BASH_COMPLETION ]; then
        # Source completion code.
        . $BASH_COMPLETION
      fi
    fi
  fi
  unset bash bminor bmajor
}

_init_bash_settings () {

  # Make bash check it's window size after a process completes
  shopt -s checkwinsize

  ulimit -S -c 0          # Don't want any coredumps
  set -o notify
  set -o noclobber
  #set -o ignoreeof
  set -o nounset
  #set -o xtrace          # useful for debuging

  # Enable options:
#  shopt -s cdspell                         # check spelling on directory changes
  shopt -s cdable_vars
  shopt -s checkhash
  shopt -s checkwinsize                    # Make bash check it's window size after a process completes
  shopt -s mailwarn
  shopt -s sourcepath
  shopt -s no_empty_cmd_completion         # bash>=2.04 only
  shopt -s cmdhist
  shopt -s histappend histreedit histverify
  shopt -s dotglob
  shopt -s extglob                         # necessary for programmable completion
  set +o nounset                           # otherwise some completions will fail

  # Disable options:
  shopt -u mailwarn
  unset MAILCHECK                          # I don't want my shell to warn me of incoming mail


  export TIMEFORMAT=$'\nreal %3R\tuser %3U\tsys %3S\tpcpu %P\n'
  export HISTCONTROL=ignoreboth
  export HISTIGNORE="&:bg:fg:ll:h"


}

red='\x1b[0;31m'
RED='\x1b[1;31m'
blue='\x1b[0;34m'
BLUE='\x1b[1;34m'
cyan='\x1b[0;36m'
CYAN='\x1b[1;36m'
NC='\x1b[0m'              # No Color 


_init_set_prompt () {

  PS1='\h:\w \u\$ '

  PROMPT="\u@\h \W> "
  PS1=$PROMPT

}



_init_run_screen 
_init_setup_editor
_init_bash_completion
_init_bash_settings
_init_set_prompt

